name: flutter_secure_storage_example
description: Demonstrates how to use the flutter_secure_storage plugin.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  lint: any
  test: any

flutter:
  uses-material-design: true
