name: integration test

on:
  - pull_request
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github

jobs:
  drive_android:
    name: Android
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        include:
          - api-level: 21
            target: default
            arch: x86
          - api-level: 34
            target: google_apis
            arch: x86_64
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.x
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "gradle"
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - name: Install melos
        run: |
          flutter pub global activate melos
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
          echo "$HOME/AppData/Local/Pub/Cache/bin" >> $GITHUB_PATH
      - name: Initialize workspace through melos
        run: melos bootstrap
      - name: Run Flutter Integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          script: flutter test integration_test
          working-directory: flutter_secure_storage/example
  drive_ios:
    name: iOS
    runs-on: macos-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.x
      - name: Install melos
        run: |
          flutter pub global activate melos
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
          echo "$HOME/AppData/Local/Pub/Cache/bin" >> $GITHUB_PATH
      - name: Initialize workspace through melos
        run: melos bootstrap
      - uses: futureware-tech/simulator-action@v3
        with:
          os: iOS
          os_version: 17.5
          model: "iPhone 15"
      - name: Run Flutter Integration tests
        working-directory: flutter_secure_storage/example
        run: flutter test integration_test
  drive_web:
    name: Web
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.x
      - name: Install melos
        run: |
          flutter pub global activate melos
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
          echo "$HOME/AppData/Local/Pub/Cache/bin" >> $GITHUB_PATH
      - name: Initialize workspace through melos
        run: melos bootstrap
      - uses: nanasess/setup-chromedriver@v2
      - name: Run Flutter Driver tests
        run: |
          set -e
          chromedriver --port=4444 & sleep 5
          flutter drive --target=test_driver/app.dart -d web-server --profile --browser-name=chrome
        working-directory: flutter_secure_storage/example
